// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpynSCRujk28Pv9-sKAgluruIBVTo8LU',
    appId: '1:670366419389:web:e864ce88d40a791d5fead4',
    messagingSenderId: '670366419389',
    projectId: 'lifelinev2-7cad5',
    authDomain: 'lifelinev2-7cad5.firebaseapp.com',
    storageBucket: 'lifelinev2-7cad5.firebasestorage.app',
    measurementId: 'G-7WYNCP2M6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSSMkMCoP9yy_FzJp_cKoK8g75okaOJeg',
    appId: '1:670366419389:android:2cf08dd81e2cc2b95fead4',
    messagingSenderId: '670366419389',
    projectId: 'lifelinev2-7cad5',
    storageBucket: 'lifelinev2-7cad5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXoFN_hlsd_yHyHRxdvOxZcu39fC4wYo',
    appId: '1:670366419389:ios:6abfd8d293972bf65fead4',
    messagingSenderId: '670366419389',
    projectId: 'lifelinev2-7cad5',
    storageBucket: 'lifelinev2-7cad5.firebasestorage.app',
    iosClientId: '670366419389-d46ijlnf9lt1ikcqgbgt0qh67fuqdmup.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXoFN_hlsd_yHyHRxdvOxZcu39fC4wYo',
    appId: '1:670366419389:ios:6abfd8d293972bf65fead4',
    messagingSenderId: '670366419389',
    projectId: 'lifelinev2-7cad5',
    storageBucket: 'lifelinev2-7cad5.firebasestorage.app',
    iosClientId: '670366419389-d46ijlnf9lt1ikcqgbgt0qh67fuqdmup.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSpynSCRujk28Pv9-sKAgluruIBVTo8LU',
    appId: '1:670366419389:web:0a27b02f748b2c115fead4',
    messagingSenderId: '670366419389',
    projectId: 'lifelinev2-7cad5',
    authDomain: 'lifelinev2-7cad5.firebaseapp.com',
    storageBucket: 'lifelinev2-7cad5.firebasestorage.app',
    measurementId: 'G-20ZND9EGC1',
  );

}