// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuu-XsOJmkASqOuhuE7dfY7u2xuvq2cY',
    appId: '1:108936893907:web:c6af5da2f467aeab9d4b26',
    messagingSenderId: '108936893907',
    projectId: 'lifeline-4e98c',
    authDomain: 'lifeline-4e98c.firebaseapp.com',
    storageBucket: 'lifeline-4e98c.firebasestorage.app',
    measurementId: 'G-TEV7RQRG6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeU_1OgU-cTLqdv4PhWp9-vcSnDpBDnQ',
    appId: '1:108936893907:android:8df9eb432e5fcba89d4b26',
    messagingSenderId: '108936893907',
    projectId: 'lifeline-4e98c',
    storageBucket: 'lifeline-4e98c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa9KTdahgnkyu1s8XEfB6D_2fjgY5YjE4',
    appId: '1:108936893907:ios:a954af17f7b297bb9d4b26',
    messagingSenderId: '108936893907',
    projectId: 'lifeline-4e98c',
    storageBucket: 'lifeline-4e98c.firebasestorage.app',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa9KTdahgnkyu1s8XEfB6D_2fjgY5YjE4',
    appId: '1:108936893907:ios:a954af17f7b297bb9d4b26',
    messagingSenderId: '108936893907',
    projectId: 'lifeline-4e98c',
    storageBucket: 'lifeline-4e98c.firebasestorage.app',
    iosBundleId: 'com.example.lifeline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWuu-XsOJmkASqOuhuE7dfY7u2xuvq2cY',
    appId: '1:108936893907:web:f999cfa5408681629d4b26',
    messagingSenderId: '108936893907',
    projectId: 'lifeline-4e98c',
    authDomain: 'lifeline-4e98c.firebaseapp.com',
    storageBucket: 'lifeline-4e98c.firebasestorage.app',
    measurementId: 'G-12V9V9XZE2',
  );
}
